name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        ./gradlew linkReleaseExecutableNative
        ls -la build/bin/native/releaseExecutable/
      shell: bash
    - uses: 'actions/upload-artifact@v2'
      with:
          name: App-${{ matrix.os }}
          path: build/bin/native/releaseExecutable/untitled.kexe
