name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        ./gradlew runReleaseExecutableNative
    - uses: 'actions/upload-artifact@v2'
      with:
          name: App-${{ matrix.os }}
          path: ${{ github.workspace }}
